# bootc-image-builder configuration for tholdyos-ad

[[customizations.disk.partitions]]
fs_type = "btrfs"
mountpoint = "/"
minsize = "4 GiB"

# Local admin user
[[customizations.user]]
name = "local-admin"
groups = ["wheel"]
password = "$6$IkRLyAcOeRh62F4/$V8hvWX0ZgS/xpnFSgEWN8E64F8p3bAtEvTtG.lQdZqjYc5E56RkhM./qeCNFmkzbXKOJ0nRci/tFAa2B52bap1"
